cmake_minimum_required(VERSION 4.1)
project(proiect2poo)

set(CMAKE_CXX_STANDARD 20)

add_executable(proiect2poo main.cpp
        Data.cpp
        Data.h
        Turneu.cpp
        Turneu.h
        Persoana.cpp
        Persoana.h
        Jucator.cpp
        Jucator.h
        JucatorPro.cpp
        JucatorPro.h
        Arbitru.cpp
        Arbitru.h
        Partida.cpp
        Partida.h
)
